# Generated by Django 4.2.4 on 2023-11-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='speaker',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='nothing', max_length=255, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default=0, max_length=4, verbose_name='类型'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
